<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE order [
<!ELEMENT order (tractors+)>
<!ELEMENT tractors (tractor)>
<!ELEMENT tractor (component+)>
<!ELEMENT componets (component)>
<!ELEMENT component (manufacturerName,deliveryDate?,fragile?)>
<!ELEMENT deliveryDate (day*,month,year)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT manufacturerName (#PCDATA)>

]>


<order>
    <tractors>
        <tractor>
            <component>
                <manufacturerName></manufacturerName>
                <deliveryDate>
                    <day></day>
                    <month></month>
                    <year></year>
                </deliveryDate>
            </component>
        </tractor>
    </tractors>
</order>