=== himylxn/DAW1/Lenguajes/Ejercicios/UD04-Validating XML documents/prueba2.xml/agenda.dtd
<!ELEMENT agenda (contacto)>
<!ELEMENT contacto (nombre,apellidos,direccion)>
<!ATTLIST nombre id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT direccion (calle,poblacion,cp)>

=== himylxn/DAW1/Lenguajes/Ejercicios/UD04-Validating XML documents/prueba2.xml/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">


<agenda>
    <contacto>
        <nombre id="234">Juan</nombre>
        <apellidos>Perez Lopez</apellidos>
        <direccion>
            <calle>Norte</calle>
            <poblacion>Alcazar</poblacion>
            <cp>15079</cp>
        </direccion>
    </contacto>
</agenda>
