<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE parents [
    <!ELEMENT parents (son+,daughter+)>
    <!ELEMENT son (#PCDATA)>
    <!ELEMENT daughter (#PCDATA)>
]>

<parents>
    <son>Anxo</son>
    <son>Ricardo</son>
    <daughter>Nerea</daughter>
    <daughter>Jorjita</daughter>
    <daughter>Pelotuda</daughter>
</parents>