=== himylxn/DAW1/Lenguajes/Ejercicios/UD04-Validating XML documents/XSD_pruebas/preba2/ejemplo1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="transportes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aereos" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence minOccurs="0">
                            <xs:element name="avion" minOccurs="0" type="xs:string" />
                            <xs:element name="helicoptero" minOccurs="0" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="terrestres">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="coche" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="numeros" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== himylxn/DAW1/Lenguajes/Ejercicios/UD04-Validating XML documents/XSD_pruebas/preba2/ejemplo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<transportes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejemplo1.xsd">
    <aereos>
        <avion>vuela lejos colega</avion>
    </aereos>
    <aereos>
        <helicoptero>vuela menos lejos colega</helicoptero>
    </aereos>
    <terrestres>
        <coche>es muy usado</coche>
    </terrestres>
    <numeros>2</numeros>
</transportes>
