<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE suplies [

    <!ELEMENT suplies (tractor+)>
    <!ELEMENT tractor (component+)>
    <!ELEMENT component (manufacturerName,deliveryDate?,weight)>
    <!ATTLIST component fragile (yes | no) "yes">
        <!ELEMENT manufacturerName (#PCDATA)>
        <!ELEMENT deliveryDate (day?,month,year)>
            <!ELEMENT day (#PCDATA)>
            <!ELEMENT month (#PCDATA)>
            <!ELEMENT year (#PCDATA)>
        <!ELEMENT weight (serialNumber,maximumKM?)>
        <!ATTLIST weight units (Kilos | Grams) "Kilos" >
            <!ELEMENT serialNumber (#PCDATA)>
            <!ELEMENT maximumKM (#PCDATA)>
]>

<suplies>
    <tractor>
        <component fragile="yes">
            <manufacturerName></manufacturerName>
            <deliveryDate>
                <month></month>
                <year></year>
            </deliveryDate>
            <weight units="Grams">
                <serialNumber></serialNumber>
                <maximumKM></maximumKM>
            </weight>
        </component>
        <component fragile="no">
            <manufacturerName></manufacturerName>
            <weight units="Kilos">
                <serialNumber></serialNumber>
            </weight>
        </component>
    </tractor>
</suplies>