<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE library [
    <!ELEMENT library (book|journal|misc)*>
        <!ELEMENT book (author*,title?,editor?,publisher?,volume?,year?)>
        <!ATTLIST book id NMTOKEN #REQUIRED>
        <!ELEMENT journal (author*,title?,editor?,publisher?,volume?,year?)>
        <!ATTLIST journal id NMTOKEN #REQUIRED publ_year NMTOKEN #REQUIRED>
        <!ELEMENT misc (author*,title?,editor?,publisher?,volume?,year?,pages*)>
        <!ATTLIST misc id NMTOKEN #REQUIRED id2 NMTOKEN #REQUIRED>
            <!ELEMENT author (#PCDATA)>
            <!ELEMENT title (#PCDATA)>
            <!ELEMENT editor (#PCDATA)>
            <!ELEMENT publisher (#PCDATA)>
            <!ELEMENT volume (#PCDATA|number)*>
            <!ELEMENT year (#PCDATA)>
            <!ELEMENT pages (#PCDATA)>
                <!ELEMENT number (#PCDATA)>
]>

<library>
    <book id="2003-Blanken">
        <title>Intelligent XML Search</title>
        <editor>Henk A. Blanken et al.</editor>
        <publisher>Springer Verlag</publisher>
    </book>
    <journal id="TODS_1_2003" publ_year="2003">
        <title>ACM Transactions on Databases</title>
        <volume>24<number>1</number></volume>
    </journal>
    <misc id="Dipl2002-12" id2="TR2002-01-04">
        <author>U. Known</author>
        <title>The Diploma Thesis that didnâ€™t appear</title>
        <year>2002</year>
        <pages>0</pages>
    </misc>
</library> 